import turtle as trtl
painter = trtl.Turtle()

size=input("What pensize would you like?")
painter.pensize(size)
painter.penup()
painter.right(90)
painter.forward(100)
painter.left(90)
painter.pendown()
fillcolor=input("What fill color would you like for the big circle?")
painter.fillcolor(fillcolor)
painter.begin_fill()
painter.circle(100,360)
painter.end_fill()
painter.penup()
painter.left(90)
painter.forward(250)
painter.left(90)
painter.pendown()
fillcolor2=input("What fill color would you like for the big triangle?")
painter.fillcolor(fillcolor2)
painter.begin_fill()
painter.circle(140,360,3)
painter.end_fill()
painter.penup()
painter.right(180)
fillcolor3=input("What fill color would you like for the three triangles?")
painter.pendown()
painter.fillcolor(fillcolor3)
painter.begin_fill()
painter.circle(20,360,3)
painter.end_fill()
painter.penup()
painter.right(90)
painter.forward(210)
painter.right(90)
painter.forward(120)
painter.right(50)
painter.pendown()
painter.fillcolor(fillcolor3)
painter.begin_fill()
painter.circle(20,360,3)
painter.end_fill()
painter.penup()
painter.right(130)
painter.forward(240)
painter.right(130)
painter.pendown()
painter.fillcolor(fillcolor3)
painter.begin_fill()
painter.circle(20,360,3)
painter.end_fill()
painter.penup()
painter.right(50)
painter.goto(-35,0)
painter.left(90)
painter.pendown()
fillcolor4=input("What fill color would you like for the medium circle?")
painter.fillcolor(fillcolor4)
painter.begin_fill()
painter.circle(35,360)
painter.end_fill()
painter.penup()
painter.backward(20)
painter.right(90)
painter.forward(10)
fillcolor5=input("What fill color would you like for the two small circles?")
painter.pendown()
painter.fillcolor(fillcolor5)
painter.begin_fill()
painter.circle(15,360)
painter.end_fill()
painter.penup()
painter.right(180)
painter.forward(90)
painter.right(180)
painter.pendown()
painter.begin_fill()
painter.circle(15,360)
painter.end_fill()
print("There is your finished drawing")
print("Enjoy :D")


wn = trtl.Screen()
wn.mainloop()